name: update-covid-data
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # check out repository and download it to the runner -> to run actions against code

      - name: setup python
        uses: actions/setup-python@v2 # install python
        with:
          python-version: "3.6.13"

      - name: update data
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python python data_process.py ${{ secrets.COVID_DASHBOARD_SOURCE }} ${{ secrets.GISAID_URL }} ${{ secrets.GISAID_USERNAME }} ${{ secrets.GISAID_PASSWORD}}
          Rscript source/dashboard_tables.R


      - name: commit files
        run: |
          git config --local user.email "joicy.xavier7@gmail.com"
          git config --local user.name "joicy"
          git add -A
          git commit -m "update data" -a

      - name: push to repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main